ghc: 7.8
script:
- ghc --make site.hs
- "./site build"
- cd ./_site
- git commit -am "travis commit ${TRAVIS_COMMIT}"
- git push
env:
  global:
    secure: FOLjr4DDZa4PRhSwE5RmufOK6peR/+cluZhYqCNKnnmsUlQc1UPzTTqBpxoFlbsbd7IEw+RfA8dcAnqg+hm/c+0bMnfeWHnUCHJ8B+FZMW43PWrUVcu9TeRGiFQUIlGmwS/I2HqUONkngbke+l05TU7TGqbAyO59o6E9pB+zK4w=
