ghc: 7.8
script:
- "./build.sh"
after_success:
- "./deploy.sh"
env:
  global:
  - secure: kVev4R3PKNLE+xpWSbk//793VJJ6KZSqbEbBdjOM/wDrjsYwuZ6YQiY49UL+Dx+DVrEhXmiOV8aIkSZRBNxBUmL0Li00jaYXGEaGS5cAsVorGeMozWRIBkaJuhlzHiY9PFJ1q3RfoyokslK/A4dVJD87yYPvNC8xAokxlnCoh+4=
