ghc: 7.8
script:
  - "./build.sh"
after_success:
  - "./deploy.sh"
env:
  global:
    secure: mCyaRB824+kSrlgUAKgwL/k5zhSwOIcNIahBFYok/+3iRZ7shYkhOwvv7zJi90ByVrXL252vH2jQWWZuUKTnK8tMOOHm1FRvPV8ad++zLt+KhpDRjjGYywypB4+YxUD/7LMCNeTdKXZVCdepFxe2sHD+uDNdY44YmliYtY+zAlo=
