#!/usr/bin/env bash
# Derived from http://zonca.github.io/2013/09/automatically-build-pelican-and-publish-to-github-pages.html


_this=$(readlink -f ${BASH_SOURCE})
_here=$(dirname ${_this})
echo "\${_this} == \"${_this}\""
echo "\${_here} == \"${_here}\""

if [[ "true" == "${TRAVIS}" ]]
then
    git config --global user.email "travis@travis-ci.org"
    git config --global user.name "Travis CI"
else
    GITHUB_TOKEN="75ae90656c798fe990fb8a950323cc2a8a2e6a84"
fi

cd ${_here}

# Pull message and hash from most recent commit
_mess=$(git log -1 --pretty=%B)
_hash=$(git rev-parse HEAD)

_repo=https://${GITHUB_TOKEN}@github.com:rubicks/rubicks.github.io.git
_tdir=$(mktemp -d)

echo "\${_repo} == \"${_repo}\""
echo "\${_tdir} == \"${_tdir}\""

git clone    \
    --quiet  \
    --       \
    ${_repo} \
    ${_tdir}

cp --verbose                   \
   --recursive                 \
   --target-directory ${_tdir} \
   ${_here}/_site/*

cd ${_tdir}

git add --all

git status --branch --short

if [[ "true" == "${TRAVIS}" ]]
then
    git commit \
        -m "$commitMessage" \
        -m "Generated by commit $commitHash; pushed by Travis build $TRAVIS_BUILD_NUMBER."
else
    git commit \
        -m "$commitMessage" \
        -m "Generated by commit $commitHash."
fi

git push --force origin master

cd ${_here}
