#!/usr/bin/env bash
# Derived from http://zonca.github.io/2013/09/automatically-build-pelican-and-publish-to-github-pages.html


_this=$(readlink -f ${BASH_SOURCE})
_here=$(dirname ${_this})
echo "\${_this} == \"${_this}\""
echo "\${_here} == \"${_here}\""


BRANCH=master
# PELICAN_OUTPUT_FOLDER=output
# REMOTE_OUTPUT_FOLDER=remote-site

if [ "$TRAVIS" == "true" ]; then
    git config --global user.email "travis@travis-ci.org"
    git config --global user.name "Travis CI"
else
    GITHUB_TOKEN="git" # set GH_TOKEN variable to "git" for correct GITHUB_REPO URL
fi

# Pull hash and commit message of most recent commit
commitHash=`git rev-parse HEAD`
commitMessage=`git log -1 --pretty=%B`

# Clone the GitHub Pages branch and rsync it with the newly generated files
GITHUB_REPO=${GITHUB_TOKEN}@github.com:rubicks/rubicks.github.io.git


cd ${_here}

rm -vrf ${_here}/rubicks.github.io

mkdir -vp ${_here}/rubicks.github.io

git clone ${GITHUB_REPO} ${_here}/rubicks.github.io

cp -v -r -t ${_here}/rubicks.github.io ${_here}/_site/*

cd ${_here}/rubicks.github.io

git add --all

git status --branch --short

if [[ "true" == "${TRAVIS}" ]]
then
    git commit \
        -m "$commitMessage" \
        -m "Generated by commit $commitHash; pushed by Travis build $TRAVIS_BUILD_NUMBER."
else
    git commit \
        -m "$commitMessage" \
        -m "Generated by commit $commitHash."
fi

git push --force origin master

cd ${_here}
